# Header
nav:
  Posts: /archives
  Categories: /category
  Tags: /tag

# favicon
favicon: /favicon.png

# logo
logo: /images/logo.svg

# links
links:
  Github: https://github.com/xbmlz
  ZhiHu: https://github.com/xbmlz
  Twitter: https://github.com/xbmlz
  Weibo: https://github.com/xbmlz

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable: true
  repo: xbmlz/maple-giscus
  repo_id: R_kgDOIgC6Zg
  category: General
  category_id: DIC_kwDOIgC6Zs4CSwIE
  mapping: pathname



